apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ubuntu
resources:
- ../../base/ubuntu
images:
- name: ubuntu
  newTag: "20.04" # {"$imagepolicy": "flux-system:ubuntu-calver:tag"}
