apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo-helm
resources:
- ../../base/podinfo-helm
patches:
- target:
    kind: HelmRelease
    name: podinfo
  patch: |-
    - op: add
      path: /spec/values
      value:
        image:
          tag: 5.0.0 # {"$imagepolicy": "flux-system:podinfo:tag"}
