apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo-kustomize
resources:
- ../../base/podinfo-kustomize
images:
- name: podinfo
  newName: podinfo # {"$imagepolicy": "flux-system:podinfo:image"}
  newTag: 5.2.0 # {"$imagepolicy": "flux-system:podinfo:tag"}
