apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo-kustomize
resources:
- ../../base/podinfo-kustomize
images:
- name: podinfo
  newName: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "flux-system:podinfo:name"}
  newTag: 5.1.4 # {"$imagepolicy": "flux-system:podinfo:tag"}
