apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../base
patches:
  - target:
      kind: ImageUpdateAutomation
      name: flux-system
    patch: |-
      - op: add
        path: /spec/update/path
        value: ./apps/local-kind
  - target:
      kind: podinfo
      name: flux-system
    patch: |-
      - op: replace
        path: /spec/policy/semver/range
        value: ~5.2.0
